apiVersion: v1
kind: Pod
metadata:
  name: k8s-demo
  labels:
    app.kubernetes.io/name: k8s-demo
spec:
  containers:
    - name: k8s-demo
      image: docker.io/taldockerid/k8s-demo:2.0.3
      imagePullPolicy: IfNotPresent
      env:
      - name: PORT
        value: "4321"
      - name: ENVIRONMENT
        value: "dev"
      - name: FLASK_ENV
        value: "dev"
      ports:
        - containerPort: 4321
          name: http